# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-ff85a4e4-edc5-4c74-aabc-a20f9f6927f7";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  boot.initrd.luks.devices."luks-ff85a4e4-edc5-4c74-aabc-a20f9f6927f7".device =
    "/dev/disk/by-uuid/ff85a4e4-edc5-4c74-aabc-a20f9f6927f7";

  # Encrypted swap partition for hibernate support
  boot.initrd.luks.devices."luks-33a2c874-f370-46ab-a252-5dca64198209".device =
    "/dev/disk/by-uuid/33a2c874-f370-46ab-a252-5dca64198209";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8A0B-24C8";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-33a2c874-f370-46ab-a252-5dca64198209"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
