# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-b1b26a55-fa2f-404c-9a4e-1b61c4418c81";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  boot.initrd.luks.devices."luks-b1b26a55-fa2f-404c-9a4e-1b61c4418c81".device =
    "/dev/disk/by-uuid/b1b26a55-fa2f-404c-9a4e-1b61c4418c81";

  boot.initrd.luks.devices."luks-02408d0b-15ca-4bcb-ad96-0c3bfe1007c9".device =
    "/dev/disk/by-uuid/02408d0b-15ca-4bcb-ad96-0c3bfe1007c9";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/01E8-9678";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-02408d0b-15ca-4bcb-ad96-0c3bfe1007c9"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
