# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-4cdecb90-8f5e-42fe-a634-0fb20ffabfa7";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  boot.initrd.luks.devices."luks-4cdecb90-8f5e-42fe-a634-0fb20ffabfa7".device =
    "/dev/disk/by-uuid/4cdecb90-8f5e-42fe-a634-0fb20ffabfa7";

  # Encrypted swap partition for hibernate support
  boot.initrd.luks.devices."luks-b352d890-9c18-4971-a03a-b24774f928aa".device =
    "/dev/disk/by-uuid/b352d890-9c18-4971-a03a-b24774f928aa";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1003-27F7";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-b352d890-9c18-4971-a03a-b24774f928aa"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
